bin: refactor git-ignore script
- use `local` for variables
- `exit` instead of `return` for errors

diff --git a/bin/git-ignore b/bin/git-ignore
--- a/bin/git-ignore
+++ b/bin/git-ignore
@@ -1,24 +1,23 @@
 #!/usr/bin/env bash
 
 main() {
-    if [ $# -ne 1 ]; then
+    if [ "$#" -ne 1 ]; then
         echo "Usage: $0 <lang>"
-        return 1
+        exit 1
     fi
 
-    lang="${1^}"
-    url="https://raw.githubusercontent.com/github/gitignore/main/${lang}.gitignore"
+    local lang="${1^}"
+    local url="https://raw.githubusercontent.com/github/gitignore/main/${lang}.gitignore"
 
     local response
-
     if ! response=$(curl -fsL "$url"); then
-        echo "Error: no .gitignore found for $lang" >&2
-        return 1
+        echo "Error: No .gitignore found for $lang" >&2
+        exit 1
     fi
 
     echo "$response" >>.gitignore
     echo ".gitignore for $lang added."
-    return 0
+    exit 0
 }
 
 main "$@"
