scripts: fix gitignore script

diff --git a/scripts/git-ignore b/scripts/git-ignore
--- a/scripts/git-ignore
+++ b/scripts/git-ignore
@@ -9,10 +9,10 @@ main() {
   lang="${1^}"
   url="https://raw.githubusercontent.com/github/gitignore/main/${lang}.gitignore"
 
-  response=$(curl -sS "$url")
+  response=$(curl -fsL "$url")
 
   if [ $? -ne 0 ]; then
-    echo "Error: .gitignore was not found for $lang" >&2
+    echo "Error: no .gitignore found for $lang" >&2
     return 1
   fi
 
